<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SimplePie' => array($vendorDir . '/simplepie/simplepie/library'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Google_Service_' => array($vendorDir . '/google/apiclient-services/src'),
    'Google_' => array($vendorDir . '/google/apiclient/src'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
);
